[SURFACE]
    -1 =0 ; ResType Internal Use, Do not change !!!
     2=Sub Resolution defect; RT2D_SUBRES_DEFECT[2]
     4=Very dark surface defect ; RT2D_VERY_DARK[4]
     8=Dark Surface defect; RT2D_AREA_DARK[8] 
    16=Bright Surface defect; RT2D_AREA_BRIGHT[16]
    32=Object total defective area; RT2D_PARTICLES_AREA[32]   
    64=Object total defects count; RT2D_PARTICLES_NUMBER[64]
   128=Internal use; RT2D_REDUCE
   256=Street is too narrow;         RT2D_NARROW_STREET
   512=Ink by surface; RT2D_INK_DOT
  1024=Long dark defect ; RT2D_LENGTH_DARK
  2048=Long bright defect ; RT2D_LENGTH_BRIGHT
  4096=Big Surface Defect ; RT2D_BIG
  8192=Defect Pass Filters Criteria; RT2D_PASS_FILTER_CRITERIA
 16384=Non separated dice;                RT2D_ZERO_STREET
 32768=Die size is too big;          RT2D_OVERSIZE_DIE
 65536=Edge defect;                  RT2D_EDGE
131072=Chipping IN;                   RT2D_CHIP_IN
262144=Chipping Out;                  RT2D_CHIP_OUT
1048576=Stain;			RT2D_STAIN
2097152=Solder Discolor;	RT2D_SOLDER_COLOR
4194304=Solder Good;		RT2D_SOLDER_GOOD
8388608=Solder Ring;		RT2D_SOLDER_RING
16777216=Solder Ring Missing;	RT2D_SOLDER_RING_MISSING
33554432=Solder Ring Gap;	RT2D_SOLDER_RING_GAP
67108864=Solder Top;		RT2D_SOLDER_TOP
134217728=Solder Top Missing;	RT2D_SOLDER_TOP_MISSING
268435456=Solder Top Size;	RT2D_SOLDER_TOP_SIZE
536870912=Event Defect;	RT2D_EVENT
1073741824=Wafer Level Event Defect;	RT2D_WL_EVENT

[SOLDER]
-1 =1   ; Internal Use, Do not change !!!
1=Nominal SB; GOOD 	[1]
2=SB Mislocation X; MISSLOCATION_X [2] 	  
4=SB Mislocation Y; MISSLOCATION_Y  [4]	
8=SB too big; RADIUS_OUT [8] 
16=SB too small; RADIUS_IN [16]
32=SB Protrusion; PROTRUSION [32]
64=SB Mouse Bite; MOUSE_BITE [64]
128=SB Bridge; BRIDGE [128]
256=SB Missing (Reason 1); 				
512=SB Missing (Reason 2); 		
1024=Big SB; 		
2048=SB Diameter Ratio ;RTC_DIAMETER_RATIO		
4096=SB LSL Area;RTC_LSL_POLYGON_AREA
8192=SB USL Area;RTC_USL_POLYGON_AREA
16384=SB Not found in reference; RTC_FAILED_IN_REF
32768=Abnormal Shape ;RTC_ABNORMAL_BLOB_SHAPE
65536=SB Major Axis Too Small;RTC_MAJOR_AXIS_IN
131072=SB Major Axis Too Big;RTC_MAJOR_AXIS_OUT								RTC_MAJOR_AXIS_OUT = 131072, 
262144=SB Minor Axis Too Small;RTC_MINOR_AXIS_IN							RTC_MINOR_AXIS_IN = 262144,
524288=SB Minor Axis Too Big;RTC_MINOR_AXIS_OUT									RTC_MINOR_AXIS_OUT = 524288,
1048576=SB Angle Exceeds Spec;RTC_ANGLE_EXCEEDS_SPEC
2097152=SB Critical Size Error;RTC_CRITICAL_SIZE_ERROR
4194304=SB Mislocation; RTC_MISSLOCATION 	
8388608=Custom Classification; RTC_CUSTOM

;;;;;;;;;;;;;
[PAD]
-1 =4   ; Internal Use, Do not change !!!
1=Nominal Pad; GOOD [1]			  
2=Pad Mislocation X; MISSLOCATION_X   [2]
4=Pad Mislocation Y; MISSLOCATION_Y [4]
8=Width USL violation; UPPER_WIDTH [8]
16=Length USL violation; UPPER_HEIGH [16]
32=Width LSL violation; LOWER_WIDTH [32]
64=Length LSL violation; LOWER_HEIGH [64]
128=Pad Protrusion; PERTRUSION 	
256=Pad Bridging; BRIDGE		
512=Pad too narrow; PERCENT_WIDTH	
1024=Pad too short; PERCENT_HEIGHT  
2048=Contaminated Pad ; RTP_CONTAMINATION

[Gold]
-1 =6   ; Internal Use, Do not change !!!
1=Nominal Gold Bump; GOOD [1]			  
2=GB Mislocation X; MISSLOCATION_X   [2]
4=GB Mislocation Y; MISSLOCATION_Y [4]
8=Width USL violation; UPPER_WIDTH [8]
16=Length USL violation; UPPER_HEIGH [16]
32=Width LSL violation; LOWER_WIDTH [32]
64=Length LSL violation; LOWER_HEIGH [64]
128=Bump Protrusion; PERTRUSION 	
256=Bump Bridging; BRIDGE		
512=GB too narrow; PERCENT_WIDTH	
1024=GB too short; PERCENT_HEIGHT  
8192=Object Not Measured;

;;;;;;;;;;;;;
[PROB]
-1 =5   ; Internal Use, Do not change !!!
1=Nominal PM; GOOD [1]
2=Proximity Violation; PROXIMITY [2]
4=PM too shifted; TOUCHING_PIXELS [4]
8=PM area too small; MIN_AREA [8]
16=PM area too big; MAX_AREA [16]
32=Missing PM; MIN_PROBS  [32]                 
64=Too many PM; MAX_PROBS  [64]        
128=Too many Objects; RTP_PM_NB_OF_OBJECTS[128]
256=Pad Area is zero; RTP_PM_INVALID_PAD_AREA [256]
512=Probe on surface;[RTP_PM_TOUCHING_SURFACE]

[Height]
-1 =2   ; Internal Use, Do not change !!!
1=Nominal Height; GOOD  [1]
2=Height LSL violation (CCS); 		STIL_HEIGHT_UNDER [2]
4=Height USL violation (CCS); 		STIL_HEIGHT_ABOVE [4]
8=Shape violation (CCS); 		STIL_BUMP_BAD_QUALITY [8]
32=Height LSL violation (CTS);		IVP_HEIGHT_UNDER [32] 
64=Height USL violation (CTS);		IVP_HEIGHT_ABOVE [64]
128=Shape violation (CTS);		IVP_BAD_QUALITY [128]
256=Shape violation (CCS Reference); 	STIL_SURFACE_BAD_QUALITY [256]
512=Shape violation (CCS Stretch); 	STIL_SURFACE_STRETCH [512]
1024=Below;				RT3D_POST_UNDER 
2048=Above;				RT3D_POST_ABOVE
4096=Roughness;				RT3D_ROUGHNESS
8192=Slope;				RT3D_SLOPE
16384=Roughness StDiv; 			RT3D_ROUGHNESS_STDIV
32768=Gold Bump Defect;			RT3D_ZERO_COUNT_DEFECT
65536=Invalid CTS Data;			RT3D_IVP_INVALID_DATA
131072=Bridge Bump;				RT3D_IVP_BRIDGE
262144=Critical;				RT3D_IVP_HEIGHT_CRITICAL
524288=No Top Reflection;				RT3D_CTS_NO_TOP_REFLECTION
1048576=No Surface Reflection;				RT3D_CTS_NO_BOTTOM_REFLECTION
2097152=Missing Bump;				RT3D_IVP_MISSING
4194304=Estimated Height;				RT3D_CTS_ESTIMATED
8388608=Overllaped;						RT3D_OVERLLAPED_MISSED
16777216=Custom Classification;RT3D_CUSTOM 


;;;;;;;;;;;;;
[Topology]
-1 =11   ; Internal Use, Do not change !!!
1=Nominal Height; GOOD  [1]
2=Height LSL violation (Stil); STIL_HEIGHT_UNDER [2]
4=Height USL violation (Stil); STIL_HEIGHT_ABOVE [4]
8=Shape violation; STIL_BUMP_BAD_QUALITY [8]
32=Height LSL violation (IVP);IVP_HEIGHT_UNDER [32] 
64=Height USL violation (IVP);IVP_HEIGHT_ABOVE [64]
128=Shape violation;IVP_BAD_QUALITY [128]
256=Shape violation (Reference); STIL_SURFACE_BAD_QUALITY [256]
512=Shape violation (Stretch); STIL_SURFACE_STRETCH [512]
1024 =Below ;RT3D_POST_UNDER 
2048 =Above ;RT3D_POST_ABOVE
4096 =Roughness ;RT3D_ROUGHNESS
8192 =Slope  ;RT3D_SLOPE

;;;;;;;;;;;;;
[Coplanarity]
-1 =7   ; Internal Use, Do not change !!!
1=Nominal Coplanarity; POST_COPLANARITY_GOOD[1]
2=Coplanarity Exceeded Limit;  POST_COPLANARITY_HIGH [2]
4=Missing Data; POST_COPLANARITY_NO_POINTS[4]
8=Lowest Bump;POST_COPLANARITY_MIN [8]
16=Highest Bump;POST_COPLANARITY_MAX[16]
32=LSL Average;POST_COPLANARITY_AVG_LSL[32]
64=USL Average;POST_COPLANARITY_AVG_USL[64]
128=USL Stdiv;POST_COPLANARITY_STD_HIGH[128]

;;;;;;;;;;;;;
[InkDot]
-1 =8   ; Internal Use, Do not change !!!
;0 = No Ink Dot ; RTID_NO_ID 
1 =Ink Dot Exist (Additional/Create); RTID_EXIST 
2 =Too Long Ink Dot; RTID_TOO_LONG 
4 =Too Narrow Ink Dot ; RTID_TOO_NARROW 
8 =Misslocated Ink Dot ; RTID_MISSLOCATION 

;;;;;;;;;;;;;;;;;;
[Volume]
-1 =9   ; Internal Use, Do not change !!!
1 =Nominal Volume; POST_VOLUME_GOOD [1] 
2 =Low Volume ; POST_VOLUME_LOW [2]
4 =High Volume ; POST_VOLUME_HIGH [4]

;;;;;;;;;;;;;;;;;;
[Cluster]
-1=12   ; Internal Use, Do not change !!!
2= Cluster Area Sum Violation
4= Object Count In Cluster Violation
8= Bounding Box width violation; RT_CLUSTER_BOUNDING_WIDTH
16= Bounding Box area violation; RT_CLUSTER_BOUNDING_AREA

;;;;;;;;;;;;;;;;;;
[SBDieLevel]
-1 =13   ; Internal Use, Do not change !!!
1  =GOOD 
2 =AVERAGE_MAJOR_LSL
4 =AVERAGE_MAJOR_USL
8 =AVERAGE_MIN_TO_MAX
16 =STDIV_USL
32 =MAX_DELTA_MIC
64 =MAX_DELTA_PERCENT
128=AVERAGE_MINOR_LSL
256=AVERAGE_MINOR_USL

;;;;;;;;;;;;;;;;;;
[Line Measure]
-1 = 14   ; Internal Use, Do not change !!!
1 = Good	
2 = Min Width Violation
4 = Max Width Violation
8 = Misslocation
16 = Opening Start
32 = Opening End
64 = Merged Line 

;;;;;;;;;;;;;;;;;;
[Street]
-1=15
1 =Good	
2 =Chipping
4 =Street Too Narrow
8 =Offset
16=Proximity
32=Street Too Wide
1024 = Street too left

;;;;;;;;;;;;;;;;;;
[Object Miss Registration]
-1=16
1 = Good
2 = Outer Object Not Found
4 = Inner Object Not Found
8 = Miss Registration X Above Spec
16 = Miss Registration Y Above Spec
32 = Low Inner Object Fitting Score
64 = Low Outer Object Fitting Score
128 = Inner Too Close To Outer Edge
256 = Inner Exceeds Outer
512 = Inner Too Small
1024 = Inner Too Big
2048 = Outer Too Small
4096 = Outer Too Big					   
;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Planarity]
-1 =26   ; Internal Use, Do not change !!!
1=Nominal Coplanarity; POST_COPLANARITY_GOOD[1]
2=Exceeded Limit;  POST_COPLANARITY_HIGH [2]
4=Missing Data; POST_COPLANARITY_NO_POINTS[4]
8=Lowest Bump;POST_COPLANARITY_MIN [8]
16=Highest Bump;POST_COPLANARITY_MAX[16]
32=LSL Average;POST_COPLANARITY_AVG_LSL[32]
64=USL Average;POST_COPLANARITY_AVG_USL[64]
128=USL Stdiv;POST_COPLANARITY_STD_HIGH[128]

[SBOutlierInDie]
-1=30   ; Internal Use, Do not change !!!
1 = Good 
2 = Major LSL
4 = Major USL
8 = Minor LSL
16= Minor USL

[RecessPad]
-1=31
1 = Good
2 = Crater Not Found;										= 1 << 1,
4 = Crater Radius Below Spec;								= 1 << 2,
8 = Crater Radius Above Spec;								= 1 << 3,
64 = Pillar Not Found;										= 1 << 6,
128 = Pillar Radius Below Spec;								= 1 << 7,
256 = Pillar Radius Above Spec;								= 1 << 8,
1024 = Top Height Not Found;								= 1 << 10,
2048 = Top Height Below Spec;								= 1 << 11,
4096 = Top Height Above Spec;								= 1 << 12,
8192 = Bottom Height Not Found;								= 1 << 13,
16384 = Bottom Height Below Spec;							= 1 << 14,
32768 = Bottom Height Above Spec;							= 1 << 15,
65536 = Left Height Not Found;								= 1 << 16,
131072 = Left Height Below Spec;							= 1 << 17,
262144 = Left Height Above Spec;							= 1 << 18,
524288 = Right Height Not Found;							= 1 << 19,
1048576 = Right Height Below Spec;							= 1 << 20,
2097152 = Right Height Above Spec;							= 1 << 21,
4194304 = Crater To Pillar Center Distance Above Spec;		= 1 << 22,
8388608 = Object Not Found;									= 1 << 23,
16777216 = Object Not In Center;							= 1 << 24,		
33554432 = Segment Missing;									= 1 << 25,	
67108864 = Tilt Violation;									= 1 << 26,
134217728 = Out of Focus;									= 1 << 27,

[HeightSurveyor3D]
-1 = 47								; Internal Use, Do not change !!!					
1 = Good;
2 = Invalid Data;											= 1 << 1,
4 = Invalid Image Data; 									= 1 << 2,
8 = Invalid Number Of Layers;								= 1 << 3,
16 = Height Below Spec;										= 1 << 4,
32 = Height Above Spec;										= 1 << 5,
64 = Reference And Target Are The Same;						= 1 << 6,
128 = Point On Reference Is Out Of Bound;					= 1 << 7,

[DieLocation]
-1=32
1 = Good
2 = Alignment Missing
4 = Shift X Max
8 = Shift Y Max
16 = Rotation
32 = Rotation Rel
64 = Shift X Min
128 = Shift Y Min

[Metrology]
-1=34
1 = Good				;RTMET_GOOD				= 1<<0
2 = LSL Violation       ;RTMET_LSL				= 1<<1,
4 = USL Violation       ;RTMET_USL				= 1<<2
8 = Out Of Spec         ;RTMET_OUT_OF_SPEC		= 1<<3,
16 = Not Found          ;RTMET_NOT_MEASURED		= 1<<4

;;;;;;;;;;;;;;;;;;
[RDL Measure]
-1=35	; Internal Use, Do not change !!!
1 =Good	
2 =Not Measured
4 =X Above Spec
8 =Y Above Spec
16=X Under Spec
32=Y Under spec							
64=Roi 1 Percent Under Spec
128=Roi 2 Percent Under Spec
256=General Measurement Above Spec
512=General Measurement Under Spec

[CS_Overlay]
-1=36	; Internal Use, Do not change !!!
1 =Good	
2 =Reference Not Found
4 =Local Not Found
8 =Local Not Measured
16=X Above Spec
32=Y Above Spec
64=Angle Above spec	
128=Size Violation Spec
256=Shifted Up
512=Shifted Down
1024=Partial In Frame						

[EBR Measure] 
-1=38	; Internal Use, Do not change !!!
1 =Good	
2 =Not Measured
4 =Measurement Above Spec
8 =Measurement Below Spec	

[Bsi] 
-1=40	; Internal Use, Do not change !!!
1 =Good	
2 =Wafer Failed;RTBSI_WAFER_FAILED	= 1 << 1,
4 =Die Failed;RTBSI_DIE_FAILED	= 1 << 2,
8 =Info Only;RTBSI_INFO_ONLY		= 1 << 3
				
[Zone Coplanarity]
-1 =41   ; Internal Use, Do not change !!!
1=Plane Nominal Coplanarity; POST_COPLANARITY_GOOD[1]
2=Plane Coplanarity Exceeded Limit;  POST_COPLANARITY_HIGH [2]
4=Plane Missing Data; POST_COPLANARITY_NO_POINTS[4]
8=Plane Lowest Bump;POST_COPLANARITY_MIN [8]
16=Plane Highest Bump;POST_COPLANARITY_MAX[16]
32=Plane LSL Average;POST_COPLANARITY_AVG_LSL[32]
64=Plane USL Average;POST_COPLANARITY_AVG_USL[64]
128=Plane USL Stdiv;POST_COPLANARITY_STD_HIGH[128]
256=Plane Height Delta Above USL ; POST_COPLANARITY_ABOVE_AVG_HEIGHT_DELTA[256]
512=Plane Height Delta below LSL ; POST_COPLANARITY_BELOW_AVG_HEIGHT_DELTA[512]
1024=Plane Cop. Delta Exceed Limit ; POST_COPLANARITY_MAX_COPLANARITY_DELTA[1024]

[OCR]
-1 =22   ; Internal Use, Do not change !!!
1 =Good	
2=ID READER NOT FOUND; 
4=ID READER MISMATCH; 

[Repeated Defect]
-1=45	; Internal Use, Do not change !!!
1=Good
2=Repeated Defect ; RTREPEATER_DEFECT = 2

[BumpsSampling]	; enum EResultTypeCcsSurfaceAnalysisRes
-1=19					; Internal Use, Do not change !!!
1=Good					;RT_CCS_SURF_ANALIS_GOOD			
2=Below Spec			;RT_CCS_SURF_ANALIS_BELOW_SPEC	
4=Above Spec			;RT_CCS_SURF_ANALIS_ABOVE_SPEC	
8=Min Allowed Thikness	;RT_CCS_SURF_ANALIS_MIN_THIKN	
16=Max Allowed Thikness	;RT_CCS_SURF_ANALIS_MAX_THIKN	
